### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by hfr2015** [LIIHWF/AdvSce#1]
Hello~,
Are there some instructions about how to start?

**Comment by LIIHWF** [comment]
To start the simulation, you need to install LGSVL Simulator and Apollo Autopilot (<= 7.0).

This repository has been integrated into [ComOpT](https://github.com/safeautonomy/ComOpT). You can follow the instructions there to try out the features.

Some of the dependent tools are deprecated. We are adapting to the new simulators and autopilots.
